"""Add examples field to enhancements table

Revision ID: dc83b8ed7bef
Revises: 883d0e439d17
Create Date: 2025-05-13 11:56:34.177351

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "dc83b8ed7bef"
down_revision: Union[str, None] = "883d0e439d17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)

    if "enhancements" in inspector.get_table_names():
        columns = [c["name"] for c in inspector.get_columns("enhancements")]
        if "examples" not in columns:
            op.add_column(
                "enhancements", sa.Column("examples", sa.Text(), nullable=True)
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("enhancements", "examples")
    # ### end Alembic commands ###
