version: "3.8"
services:
  api:
    build: .
    # Use the PORT env var if set, otherwise default to 9103
    ports:
      - "${PORT:-9103}:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: ["uvicorn", "rule_api_server:app", "--host", "0.0.0.0", "--reload"]

  test:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - ENVIRONMENT=test
    command: ["pytest", "test_rule_api_server.py"]

  coverage:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: ["pytest", "--cov=rule_api_server", "--cov-report=term-missing", "test_rule_api_server.py"]

  frontend:
    build:
      context: ./admin-frontend
      args:
        VITE_API_BASE_URL: "http://localhost:${PORT:-9103}"
    ports:
      - "${ADMIN_FRONTEND_PORT:-3000}:80"
    depends_on:
      - api
    environment:
      - VITE_API_BASE_URL=http://localhost:${PORT:-9103}

  rules-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rulesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - rules_postgres_data:/var/lib/postgresql/data

  pgloader:
    image: local/pgloader:latest
    depends_on:
      - rules-postgres
    volumes:
      - ./:/data
    entrypoint: ["/bin/sleep", "infinity"]  # For one-off exec usage

volumes:
  rules_postgres_data: 