FROM python:3.11-slim

WORKDIR /scripts

COPY misc_scripts/requirements.txt /scripts/requirements.txt

RUN apt-get update && \
    apt-get install -y postgresql-client git && \
    pip install --upgrade pip && \
    pip install -r /scripts/requirements.txt && \
    rm -rf /var/lib/apt/lists/*

COPY misc_scripts/ /scripts/
COPY . /code

CMD ["tail", "-f", "/dev/null"] 