FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
COPY . .
ENV PYTHONPATH=/app
RUN pip install -r requirements.txt
CMD ["python", "worker/main.py"] 