"""add hierarchical scope fields to enhancements

Revision ID: abdfe1c4c174
Revises: d912b78b75b4
Create Date: 2025-05-21 01:11:45.349633

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "abdfe1c4c174"
down_revision: Union[str, None] = "c4a7f0b45182"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)

    if "enhancements" in inspector.get_table_names():
        columns = [c["name"] for c in inspector.get_columns("enhancements")]

        # Add columns if they don't exist
        if "scope_level" not in columns:
            op.add_column(
                "enhancements", sa.Column("scope_level", sa.String(), nullable=True)
            )
        if "scope_id" not in columns:
            op.add_column(
                "enhancements", sa.Column("scope_id", sa.String(), nullable=True)
            )
        if "parent_rule_id" not in columns:
            op.add_column(
                "enhancements", sa.Column("parent_rule_id", sa.String(), nullable=True)
            )

        # Create indexes if they don't exist
        indexes = [idx["name"] for idx in inspector.get_indexes("enhancements")]
        if "ix_enhancements_scope_id" not in indexes:
            op.create_index(
                op.f("ix_enhancements_scope_id"),
                "enhancements",
                ["scope_id"],
                unique=False,
            )
        if "ix_enhancements_scope_level" not in indexes:
            op.create_index(
                op.f("ix_enhancements_scope_level"),
                "enhancements",
                ["scope_level"],
                unique=False,
            )

        # Update scope_level if it's NULL
        op.execute("UPDATE enhancements SET scope_level = '' WHERE scope_level IS NULL")
        op.alter_column("enhancements", "scope_level", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enhancements_scope_level"), table_name="enhancements")
    op.drop_index(op.f("ix_enhancements_scope_id"), table_name="enhancements")
    op.drop_column("enhancements", "parent_rule_id")
    op.drop_column("enhancements", "scope_id")
    op.drop_column("enhancements", "scope_level")
    # ### end Alembic commands ###
