"""Migrate all id and project_id columns to UUID type

Revision ID: c8b957ff43ca
Revises: 7728045323ee
Create Date: 2025-05-25 14:27:00.129330

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "c8b957ff43ca"
down_revision: Union[str, None] = "7728045323ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "enhancements",
        "proposal_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="proposal_id::uuid",
    )
    op.alter_column(
        "enhancements",
        "project",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="project::uuid",
    )
    op.alter_column(
        "feedback",
        "rule_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="rule_id::uuid",
    )
    op.alter_column(
        "feedback",
        "project",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="project::uuid",
    )
    op.alter_column(
        "proposals",
        "rule_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="rule_id::uuid",
    )
    op.alter_column(
        "proposals",
        "project",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="project::uuid",
    )
    op.alter_column(
        "rule_proposal_feedback",
        "id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.alter_column(
        "rule_proposal_feedback",
        "rule_proposal_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="rule_proposal_id::uuid",
    )
    op.alter_column(
        "rule_proposal_feedback",
        "user_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="user_id::uuid",
    )
    op.alter_column(
        "rule_versions",
        "rule_id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="rule_id::uuid",
    )
    op.alter_column(
        "rule_versions",
        "project",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="project::uuid",
    )
    # PATCH: Make index drop idempotent
    bind = op.get_bind()
    bind.execute(text("DROP INDEX IF EXISTS ix_rule_versions_project;"))
    op.alter_column(
        "rules",
        "project",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="project::uuid",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rules",
        "project",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_rule_versions_project"), "rule_versions", ["project"], unique=False
    )
    op.alter_column(
        "rule_versions",
        "project",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "rule_versions",
        "rule_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "rule_proposal_feedback",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "rule_proposal_feedback",
        "rule_proposal_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "rule_proposal_feedback",
        "id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "proposals",
        "project",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "proposals",
        "rule_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "enhancements",
        "project",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "enhancements",
        "proposal_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "feedback",
        "project",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "feedback",
        "rule_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
