"""add enhancements table for suggested improvements

Revision ID: 1d3eabd51868
Revises: d4034974e03f
Create Date: 2025-05-12 04:22:03.941155

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d3eabd51868"
down_revision: Union[str, None] = "d4034974e03f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enhancements",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("suggested_by", sa.String(), nullable=True),
        sa.Column("page", sa.String(), nullable=True),
        sa.Column("tags", sa.String(), nullable=True),
        sa.Column("categories", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("proposal_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_enhancements_id"), "enhancements", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enhancements_id"), table_name="enhancements")
    op.drop_table("enhancements")
    # ### end Alembic commands ###
