"""Recreate base migration from models

Revision ID: 23b59ec9a17b
Revises: 
Create Date: 2025-06-11 12:31:42.949368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23b59ec9a17b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_error_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_proposals_id'), 'rule_proposals', ['id'], unique=False)
    op.create_table('namespace_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('allowed_project_id', sa.String(), nullable=True),
    sa.Column('permission_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['allowed_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_namespace_permissions_allowed_project_id'), 'namespace_permissions', ['allowed_project_id'], unique=False)
    op.create_index(op.f('ix_namespace_permissions_namespace'), 'namespace_permissions', ['namespace'], unique=False)
    op.create_index(op.f('ix_namespace_permissions_project_id'), 'namespace_permissions', ['project_id'], unique=False)
    op.alter_column('api_access_tokens', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('api_access_tokens', 'project_id',
               existing_type=sa.String(),
               existing_nullable=True)
    op.alter_column('api_access_tokens', 'allowed_namespaces',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key(None, 'api_access_tokens', 'projects', ['project_id'], ['id'])
    op.alter_column('bug_reports', 'user_story',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_bug_reports_id'), 'bug_reports', ['id'], unique=False)
    op.alter_column('enhancements', 'id',
               existing_type=sa.String(),
               existing_nullable=False)
    op.alter_column('enhancements', 'proposal_id',
               existing_type=sa.String(),
               existing_nullable=True)
    op.alter_column('enhancements', 'project',
               existing_type=sa.String(),
               existing_nullable=True)
    op.alter_column('enhancements', 'applies_to_rationale',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_enhancements_id'), 'enhancements', ['id'], unique=False)
    op.add_column('project_onboarding_progress', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('projects', 'id',
               existing_type=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('projects', 'default_namespace_updated_at')
    op.drop_column('projects', 'default_namespace_deleted_at')
    op.drop_column('projects', 'default_namespace_created_at')
    op.drop_column('projects', 'default_namespace_description')
    op.alter_column('proposals', 'id',
               existing_type=sa.String(),
               existing_nullable=False)
    op.alter_column('proposals', 'categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('proposals', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('proposals', 'examples',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('proposals', 'applies_to',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('proposals', 'applies_to_rationale',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'proposals', 'rules', ['rule_id'], ['id'])
    op.create_foreign_key(None, 'proposals', 'rules', ['parent_rule_id'], ['id'])
    op.alter_column('rule_proposal_feedback', 'feedback_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rule_versions', 'project',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('rule_versions', 'categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rule_versions', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rule_versions', 'examples',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rule_versions', 'applies_to',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rule_versions', 'applies_to_rationale',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('rule_versions', 'scope_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_rule_versions_scope_id'), 'rule_versions', ['scope_id'], unique=False)
    op.create_index(op.f('ix_rule_versions_scope_level'), 'rule_versions', ['scope_level'], unique=False)
    op.alter_column('rules', 'id',
               existing_type=sa.String(),
               existing_nullable=False)
    op.alter_column('rules', 'project',
               existing_type=sa.VARCHAR(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('rules', 'categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rules', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rules', 'examples',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rules', 'applies_to',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rules', 'applies_to_rationale',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('rules', 'user_story',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('rules', 'scope_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_rules_scope_id'), 'rules', ['scope_id'], unique=False)
    op.create_index(op.f('ix_rules_scope_level'), 'rules', ['scope_level'], unique=False)
    op.alter_column('teams', 'id',
               existing_type=sa.String(),
               existing_nullable=False)
    op.alter_column('use_cases', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('use_cases', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_use_cases_status'), table_name='use_cases')
    op.create_index(op.f('ix_use_cases_id'), 'use_cases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_use_cases_id'), table_name='use_cases')
    op.create_index(op.f('ix_use_cases_status'), 'use_cases', ['status'], unique=False)
    op.alter_column('use_cases', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('use_cases', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('teams', 'id',
               existing_type=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_rules_scope_level'), table_name='rules')
    op.drop_index(op.f('ix_rules_scope_id'), table_name='rules')
    op.alter_column('rules', 'scope_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rules', 'user_story',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('rules', 'applies_to_rationale',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('rules', 'applies_to',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rules', 'examples',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rules', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rules', 'categories',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rules', 'project',
               existing_type=sa.String(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('rules', 'id',
               existing_type=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_rule_versions_scope_level'), table_name='rule_versions')
    op.drop_index(op.f('ix_rule_versions_scope_id'), table_name='rule_versions')
    op.alter_column('rule_versions', 'scope_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rule_versions', 'applies_to_rationale',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('rule_versions', 'applies_to',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rule_versions', 'examples',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rule_versions', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rule_versions', 'categories',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('rule_versions', 'project',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('rule_proposal_feedback', 'feedback_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.alter_column('proposals', 'applies_to_rationale',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('proposals', 'applies_to',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('proposals', 'examples',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('proposals', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('proposals', 'categories',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('proposals', 'id',
               existing_type=sa.String(),
               existing_nullable=False)
    op.add_column('projects', sa.Column('default_namespace_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('default_namespace_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('default_namespace_deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('default_namespace_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.String(),
               existing_nullable=False)
    op.drop_column('project_onboarding_progress', 'status')
    op.alter_column('projects', 'id',
               existing_type=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_namespace_permissions_project_id'), table_name='namespace_permissions')
    op.drop_index(op.f('ix_namespace_permissions_namespace'), table_name='namespace_permissions')
    op.drop_index(op.f('ix_namespace_permissions_allowed_project_id'), table_name='namespace_permissions')
    op.drop_table('namespace_permissions')
    op.drop_index(op.f('ix_rule_proposals_id'), table_name='rule_proposals')
    op.drop_table('rule_proposals')
    op.drop_table('project_memberships')
    op.drop_table('api_error_logs')
    # ### end Alembic commands ###
