"""Change feedback_type to String in rule_proposal_feedback

Revision ID: 7728045323ee
Revises: c77f4c2517b0
Create Date: 2025-05-23 17:01:21.539385

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7728045323ee"
down_revision: Union[str, None] = "c77f4c2517b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rule_proposal_feedback",
        "feedback_type",
        existing_type=postgresql.ENUM(
            "accept", "reject", "needs_changes", name="feedbacktype"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rule_proposal_feedback",
        "feedback_type",
        existing_type=sa.String(),
        type_=postgresql.ENUM("accept", "reject", "needs_changes", name="feedbacktype"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
