"""Add examples column to proposals table

Revision ID: 883d0e439d17
Revises: bf9e065008bf
Create Date: 2025-05-13 11:44:55.030008

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "883d0e439d17"
down_revision: Union[str, None] = "bf9e065008bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_enhancements_project"), "enhancements", ["project"], unique=False
    )
    op.add_column("rule_versions", sa.Column("examples", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rule_versions", "examples")
    op.drop_index(op.f("ix_enhancements_project"), table_name="enhancements")
    # ### end Alembic commands ###
