"""add hierarchical scope fields to enhancements

Revision ID: abdfe1c4c174
Revises: d912b78b75b4
Create Date: 2025-05-21 01:11:45.349633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdfe1c4c174'
down_revision: Union[str, None] = 'c4a7f0b45182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enhancements', sa.Column('scope_level', sa.String(), nullable=True))
    op.add_column('enhancements', sa.Column('scope_id', sa.String(), nullable=True))
    op.add_column('enhancements', sa.Column('parent_rule_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_enhancements_scope_id'), 'enhancements', ['scope_id'], unique=False)
    op.create_index(op.f('ix_enhancements_scope_level'), 'enhancements', ['scope_level'], unique=False)
    op.execute("UPDATE enhancements SET scope_level = '' WHERE scope_level IS NULL")
    op.alter_column('enhancements', 'scope_level', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enhancements_scope_level'), table_name='enhancements')
    op.drop_index(op.f('ix_enhancements_scope_id'), table_name='enhancements')
    op.drop_column('enhancements', 'parent_rule_id')
    op.drop_column('enhancements', 'scope_id')
    op.drop_column('enhancements', 'scope_level')
    # ### end Alembic commands ###
