"""add diff to enhancements

Revision ID: c4a7f0b45182
Revises: 98d34407c6f1
Create Date: 2025-05-15 15:43:20.369488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a7f0b45182'
down_revision: Union[str, None] = '98d34407c6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enhancements', sa.Column('diff', sa.Text(), nullable=True))
    op.add_column('rule_versions', sa.Column('user_story', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_versions', 'user_story')
    op.drop_column('enhancements', 'diff')
    # ### end Alembic commands ###
