"""Migrate all id and project_id columns to UUID type

Revision ID: c8b957ff43ca
Revises: 7728045323ee
Create Date: 2025-05-25 14:27:00.129330

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "c8b957ff43ca"
down_revision: Union[str, None] = "7728045323ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # All op.alter_column statements for the 'rules' table have been removed from both upgrade and downgrade, as these columns are now created with the correct type in the consolidated migration.
    # PATCH: Make index drop idempotent
    bind = op.get_bind()
    bind.execute(text("DROP INDEX IF EXISTS ix_rule_versions_project;"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # All op.alter_column statements for the 'rules' table have been removed from both upgrade and downgrade, as these columns are now created with the correct type in the consolidated migration.
    # ### end Alembic commands ###
