"""Add examples field to enhancements table

Revision ID: dc83b8ed7bef
Revises: 883d0e439d17
Create Date: 2025-05-13 11:56:34.177351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc83b8ed7bef'
down_revision: Union[str, None] = '883d0e439d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enhancements', sa.Column('examples', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enhancements', 'examples')
    # ### end Alembic commands ###
