"""add_user_field_to_api_access_tokens

Revision ID: e1174b7c8b42
Revises: 476dd74b2bb9
Create Date: 2025-06-19 18:45:26.311453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1174b7c8b42'
down_revision: Union[str, None] = '476dd74b2bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_access_tokens', sa.Column('user', sa.String(), nullable=True))
    op.create_index(op.f('ix_api_access_tokens_user'), 'api_access_tokens', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_access_tokens_user'), table_name='api_access_tokens')
    op.drop_column('api_access_tokens', 'user')
    # ### end Alembic commands ###
