"""add status field to enhancements for transfer tracking

Revision ID: edeeb4090649
Revises: 1d3eabd51868
Create Date: 2025-05-12 04:31:14.338245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edeeb4090649'
down_revision: Union[str, None] = '1d3eabd51868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enhancements', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enhancements', 'status')
    # ### end Alembic commands ###
